version: '3.8'

services:
  postgres-db:
    container_name: rastochnoy_db  
    image: postgres:16
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=rastochnoy
    ports:
      - "5432:5432"
    volumes:
      - db:/data/postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
      start_period: 5s
      timeout: 3s
    networks:
      - app_network
    restart: always

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrations:/migrations
    depends_on:
      postgres-db:
        condition: service_healthy
    command: ["-path", "./migrations", "-database", "postgres://postgres:1234@rastochnoy_db:5432/rastochnoy?sslmode=disable", "up"]  
    networks:
      - app_network

  gps:
    container_name: rastochnoy_server
    build: .
    ports:
      - "1000:1000"
      - "1002:1002"
    depends_on:
      postgres-db:
        condition: service_healthy
      migrate:
        condition: service_started
    networks:
      - app_network
    restart: always

volumes:
  db:

networks:
  app_network:
    driver: bridge